const mongoose = require("mongoose");

//define a story schema for the database
const EventSchema = new mongoose.Schema({
  creator_id: String,
  creator_name: String,
  parent: String, // links to the _id of a parent trip (_id is an autogenerated field by Mongoose).
  name: String,
  location: String,
  description: String,
  cost: String,
  details: String
});

// compile model from schema
module.exports = mongoose.model("event", EventSchema);